apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  type: NodePort  # Altere para LoadBalancer se quiser acesso externo
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Altere a porta conforme necessário
