apiVersion: v1
kind: Service
metadata:
  name: rust-app-cluster-ip-svc
spec:
  type: ClusterIP
  selector:
    app: rust-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: rust-app-loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: rust-app 
  ports:
    - port: 3000
      targetPort: 3000
