apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-produto-app
  labels:
    app: pedido-produto-app
spec:
  template:
    metadata:
      name: pedido-produto-app
      labels:
        app: pedido-produto-app
    spec:
      containers:
        - name: pedido-produto-app-container
          image: 739842188003.dkr.ecr.us-east-1.amazonaws.com/rust_api:latest
          ports:
            - containerPort: 3000   
          envFrom:
          - configMapRef:
              name: app-configmap      
          resources:
            requests:
              cpu: 1m
  replicas: 1
  selector:
    matchLabels:
      app: pedido-produto-app