apiVersion: v1
kind: Service
metadata:
  name: listener-cluster-ip-svc
spec:
  type: ClusterIP
  selector:
    app: listener
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
