version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - 8080:3000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432"
      ENV: prod
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 5432:5432
