name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  coverage:
    name: Run
    uses: postech-5soat-grupo-25/tech-challenge-templates/.github/workflows/code-coverage.yml@main
