on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    name: Code Coverage
    uses: postech-5soat-grupo-25/tech-challenge-templates/.github/workflows/code-coverage.yml@main
