name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    name: Run
    uses: postech-5soat-grupo-25/tech-challenge-templates/.github/workflows/code-quality.yml@main
